// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2oxF0aCI2ydSc_8-ZNTjcU9cHOzHBX8w',
    appId: '1:205770888960:web:9ea11fecbbf047d2f645e5',
    messagingSenderId: '205770888960',
    projectId: 'graduation-project-iti-e8eba',
    authDomain: 'graduation-project-iti-e8eba.firebaseapp.com',
    storageBucket: 'graduation-project-iti-e8eba.firebasestorage.app',
    measurementId: 'G-XLFPZT5EJH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfui9LvkY9JQWRqT4DXG_Usjy0bz6Bzzc',
    appId: '1:205770888960:android:458dc8c5f8a9e9f8f645e5',
    messagingSenderId: '205770888960',
    projectId: 'graduation-project-iti-e8eba',
    storageBucket: 'graduation-project-iti-e8eba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwbFutt3qXOy2JD7JKMhlvt3J-r9nGZQ8',
    appId: '1:205770888960:ios:f28495b7d28f6633f645e5',
    messagingSenderId: '205770888960',
    projectId: 'graduation-project-iti-e8eba',
    storageBucket: 'graduation-project-iti-e8eba.firebasestorage.app',
    iosBundleId: 'com.example.gradProjectIti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwbFutt3qXOy2JD7JKMhlvt3J-r9nGZQ8',
    appId: '1:205770888960:ios:f28495b7d28f6633f645e5',
    messagingSenderId: '205770888960',
    projectId: 'graduation-project-iti-e8eba',
    storageBucket: 'graduation-project-iti-e8eba.firebasestorage.app',
    iosBundleId: 'com.example.gradProjectIti',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2oxF0aCI2ydSc_8-ZNTjcU9cHOzHBX8w',
    appId: '1:205770888960:web:f2f00475a980235cf645e5',
    messagingSenderId: '205770888960',
    projectId: 'graduation-project-iti-e8eba',
    authDomain: 'graduation-project-iti-e8eba.firebaseapp.com',
    storageBucket: 'graduation-project-iti-e8eba.firebasestorage.app',
    measurementId: 'G-LW1P3FSFDP',
  );

}